#!/usr/bin/env bash

if
  [[ -s "/Users/CloudFactory/.rvm/gems/ruby-1.9.3-p551/environment" ]]
then
  source "/Users/CloudFactory/.rvm/gems/ruby-1.9.3-p551/environment"
  exec ruby "$@"
else
  echo "ERROR: Missing RVM environment file: '/Users/CloudFactory/.rvm/gems/ruby-1.9.3-p551/environment'" >&2
  exit 1
fi
