#!/usr/bin/env bash

if
  [[ -s "/Users/CloudFactory/.rvm/gems/ruby-2.1.4/environment" ]]
then
  source "/Users/CloudFactory/.rvm/gems/ruby-2.1.4/environment"
  exec bundler "$@"
else
  echo "ERROR: Missing RVM environment file: '/Users/CloudFactory/.rvm/gems/ruby-2.1.4/environment'" >&2
  exit 1
fi
