var F={enabled:!0,frames:!1,sessionreplay:!0,auto:!0,encode:!0,version:"18.1.0",files:"/foresee/",id:"tBo4kkEFtcBIYIp5BhoUgA4C",definition:"foresee_surveydef.js",swf:{fileName:"foresee_transport.swf",scriptAccess:"always"},worker:"foresee_worker.js",embedded:!1,replay_id:"answers.com",site_id:"answers.com",attach:!1,renderer:"W3C",layout:"CENTERFIXED",triggerDelay:0,heartbeat:!0,enableAMD:!1,pools:[{path:".",sp:15}],sites:[{path:/\w+-?\w+\.(com|org|edu|gov|net|co\.uk)/},{path:".",domain:"default"}],
storageOption:"cookie",nameBackup:window.name,iframeHrefs:["frameWorker.html"],acceptableorigins:[],wc:{}};
"undefined"==typeof FSR&&function(p){function A(a,d,c){"string"==typeof a&&(a=b.global.document.getElementById(a.replace("#","")));if(a)return"string"==typeof d&&(d={src:d}),new G(a,b.r(b.r({},B),d),c)}function H(a,b){var c=[],e;for(e in a)a.hasOwnProperty(e)&&(c[e]=b(a[e]));return c}function G(a,d,c){s.isSupported(d.version)&&(a.innerHTML=s.cc(d,c),b.L&&(b.global[d.id]=b.global.document.getElementById(d.id)),b.r(this,{$c:function(){return a},Zc:function(){return d},Wc:function(){return c},Vc:function(){return a.firstChild}}))}
var b={},k=b.global=self;b.ob=864E5;b.L=!!b.global.document.attachEvent;var w=Object.prototype.hasOwnProperty,t=[],x=!1,u;b.g=function(a){return null!==a&&"undefined"!==typeof a};b.Mc=function(a){for(var b=a.length-1;0<=b;b--)for(var c=b-1;0<=c;c--)a[c]==a[b]&&a.splice(b,1);return a};b.Oc=function(a){for(var b=a.parentNode.childNodes,c,e=0,f=0;(c=b.item(e++))&&c!=a;)1==c.nodeType&&f++;return f};b.va=function(a){return"[object Array]"==Object.prototype.toString.call(a)};b.aa=function(a){if(a){if(a.length)for(var b=
a.length-1;0<=b;b--)a[b]=null;for(var c in a)if(b=typeof a[c],"function"==b||"object"==b)a[c]=null}};b.Z=function(a){return"function"==typeof a};b.gc=function(a){return"object"==typeof a};b.trim=function(a){return a.toString().replace(/\s+/g," ").replace(/^\s+|\s+$/g,"")};b.Xc=function(a){var d=a.getAttribute?a.getAttribute("id"):a.id;d&&!b.fd(d)&&(d=a.attributes.id.value);return d};b.Yb=function(a){return a.toString().replace(/([-.*+?^()|[\]\/\\])/g,"\\$1")};b.r=function(){var a=arguments,d=a[0]||
{},c=1,e=a.length,f,h,m;"object"===typeof d||b.Z(d)||(d={});e===c&&(d=this,--c);for(;c<e;c++)if(b.g(f=a[c]))for(h in f)m=f[h],d!==m&&void 0!==m&&(d[h]=m);return d};b.M=function(){};b.now=function(){return+new Date};b.shift=function(a){return a.splice(0,1)[0]};b.Ra=function(a,b){for(var c in b)if(b[c]===a)return c;return-1};b.Wb=function(){return b.global.document.location.protocol};b.ed=function(a,d){return-1!=b.Ra(a,d)};b.Ta=function(){return b.global.document.getElementById("_fsr_swfContainerv2_")};
b.Lc=function(a,d,c){var e=a.split(".");d=d[b.shift(e)];for(var f=c,h;b.g(d)&&0<e.length;)d=d[b.shift(e)];if(d){for(e=a.split(".");e.length&&(h=b.shift(e));)f=f[h]?f[h]:f[h]={};e=a.split(".");for(f=c;e.length&&(h=b.shift(e));)0<e.length?f=f[h]:f[h]=d}};b.R=function(){return b.global.document.location.href};b.ga=function(a){return encodeURIComponent(a)};b.ta=function(a){return decodeURIComponent(a)};b.Ua=function(){return b.global.document.referrer};b.xa={};b.jd=function(a,d,c){"undefined"!=typeof acs?
a=acs.makeURI(a):-1<a.indexOf("/")&&(a=a.substr(a.lastIndexOf("/")+1));c=c||b.M;var e=b.global.document.createElement(d);(d="script"===d)||(e.rel="stylesheet");e.type=d?"text/javascript":"text/css";d&&(b.L?e.onreadystatechange=function(){"loaded"!=this.readyState&&"complete"!=this.readyState||c("ok")}:e.onload=function(){c("ok")},e.onerror=function(){c("error")});e[d?"src":"href"]=0===b.Ra("//",a)?b.Wb()+a:a;a=b.global.document.getElementsByTagName("head")[0]||b.global.document.documentElement;d?
a.appendChild(e):d||(b.xa[e.href]?e=b.xa[e.href]:(b.xa[e.href]=e,a.appendChild(e)));if(!d){var f,h;"sheet"in e?(f="sheet",h="cssRules"):(f="styleSheet",h="rules");var m=setInterval(function(){try{e[f]&&e[f][h].length&&(clearInterval(m),clearTimeout(g),c(!0,e))}catch(a){}finally{}},10),g=setTimeout(function(){clearInterval(m);clearTimeout(g);c(!1,e)},200)}};b.ready=function(a,d,c){c||(c=b.global);c=c.document;c=c.readyState;d=d||1;if(b.Z(a)&&(a=function(a,d){return function(){setTimeout(function(a){return function(){a.call(b.ra);
a=null}}(a),d);a=null}}(a,d),c&&("complete"==c||"loaded"==c))){x=!0;for(t.push(a);a=b.shift(t);)a&&a.call(b.ra);return}if(!x&&b.Z(a))t.push(a);else if(x&&b.Z(a))a.call(b.ra);else if(!b.Z(a))for(x=!0;0<t.length;)(a=b.shift(t))&&a.call(b.ra);a=c=c=c=null};b.global.document.addEventListener?u=function(){-1<"complete,loaded".indexOf(b.global.document.readyState)&&(b.global.document.removeEventListener("readystatechange",u,!1),b.ready(null))}:b.L&&(u=function(){-1<"complete,loaded".indexOf(b.global.document.readyState)&&
(b.global.document.detachEvent("onreadystatechange",u),b.ready(null))});b.global.document.addEventListener?(b.global.document.addEventListener("readystatechange",u,!1),b.global.document.addEventListener("DOMContentLoaded",b.ready,!1)):b.L&&b.global.document.attachEvent("onreadystatechange",u);b.match=function(a,d){function c(a,d){b.va(d)||(d=[d]);for(var c=0,e=d.length;c<e;c++)if((a+"").match(d[c]))return!0;return!1}var e=[["urls",b.R()],["local",b.R()],["referrers",b.Ua()],["referrer",b.Ua()],["userAgents",
b.global.navigator.userAgent],["browsers",{name:BROWSER.Sa.name,version:BROWSER.Sa.Sb}]],f,h,m,g;for(m=0;m<e.length;m++){f=e[m];h=a[f[0]]||[];for(var l=0;l<h.length;l++){var k=h[l];if(!b.gc(f[1])){if(b.ta(f[1]).match(k))return!0}else if(b.ta(f[1].name.toLowerCase()).match(k.name.toLowerCase())&&(!k.version||f[1].version==k.version))return!0}}h=a.cookies||[];for(m=0;m<h.length;m++)if(f=h[m],e=b.a.e.h.N(f.name,{path:f.path,domain:f.domain}))if(!f.operator||"eq"==f.operator){if(e.match(f.value||"."))return!0}else if((f.operator||
"neq"==f.operator)&&!b.g(e.match(f.value)))return!0;if(m=a.variables)for(f=0,n=m.length;f<n;f++)if(h=m[f].name,e=m[f].value,h!=C.ipexclude||1!==d){b.va(h)||(h=[h],e=[e]);for(var q,l=!0,k=0,p=h.length,r=e.length;k<p&&k<r;k++){try{q=(new [].constructor.constructor("return "+h[k]))(),b.g(q)||(q="")}catch(s){q=""}if(!c(q,e[k])){l=!1;break}}if(l)return!0}q=a.metas||[];e=h=null;if(0<q.length)for(h=document.getElementsByTagName("meta"),m=0;m<h.length;m++)for(e=h[m],f=0;f<q.length;f++)for(g in q[f])if(c(e.getAttribute(g),
q[f][g].key)&&("undefined"===typeof q[f][g].content||c(e.getAttribute("content"),q[f][g].content)))return!0;return!1};b.startTime=b.now();var C={},l=b.r({replay_id:"sitecom",site:{domain:"site.com"},renderer:"W3C",layout:""},p||{});b.ic=function(){for(var a={},d=arguments,c=0,e=d.length;c<e;c++){var f=d[c];if(b.ha(f))for(var h in f){var g=f[h],k=a[h];a[h]=k&&b.ha(g)&&b.ha(k)?b.ic(k,g):b.Ca(g)}}return a};b.Ca=function(a){var d;if(b.ha(a)){d={};for(var c in a)d[c]=b.Ca(a[c])}else if(b.va(a)){d=[];c=
0;for(var e=a.length;c<e;c++)d[c]=b.Ca(a[c])}else d=a;return d};b.ha=function(a){if(!a||"[object Object]"!==Object.prototype.toString.call(a)||a.nodeType||a.setInterval||a.constructor&&!w.call(a,"constructor")&&!w.call(a.constructor.prototype,"isPrototypeOf"))return!1;for(var b in a);return void 0===b||w.call(a,b)||!w.call(a,b)&&w.call(Object.prototype,b)};b.t=function(){t=l=null;b.global.FSR=null;b=b.global=null};b.bd=function(a){var d=b.now(),c;do c=b.now();while(c-d<a)};b.g(p.FSRCONFIG)&&(p=p.FSRCONFIG,
p.surveydefs&&(b.surveydefs=p.surveydefs,p.surveydefs=null),p.properties&&(b.properties=p.properties,p.properties=null));k.FSR=b;k.FSR.opts=l;k.FSR.prop=C;b.a={};b.a.b={};b.a.b.Uc=function(){for(var a=b.global.navigator.userAgent.replace(/[\s\\\/\.\(\);:]/gim,""),d="",c=b.now()+"",e=0;e<a.length-1;e+=a.length/7)d+=Number(a.charCodeAt(Math.round(e))%16).toString(16);7<d.length&&(d=d.substr(d.length-7));return d+"-"+a.length+c.substr(c.length-6)+"-xxxx-xxxx-xxxxx".replace(/[xy]/g,function(a){var b=
16*Math.random()|0;return("x"==a?b:b&3|8).toString(16)})};b.a.b.lc=function(a){return 0+Math.random()*(a-0)};b.a.b.qc=function(a,d){var c=b.global.document.createElement("a");c.href=b.global.location.href;var e=c.hostname,f=c.protocol;c.href=a;var h=c.hostname||e,g=0===c.protocol.indexOf("http")?c.protocol:f;c.href=d;f=0===c.protocol.indexOf("http")?c.protocol:f;return h.toLowerCase()==(c.hostname||e).toLowerCase()&&g.toLowerCase()==f.toLowerCase()};b.a.b.Gc=function(a,b){return a+=(a.split("?")[1]?
"&":"?")+b};b.a.b.sd=function(a,d,c){var e="";if(a)for(var f in a)e+=(0!==e.length?"&":"")+(d?d+"["+f+"]":f)+"="+(c?a[f]:b.ga(a[f]));return e};b.a.b.hash=function(a){a=a.split("_");return 3*a[0]+1357+""+(9*a[1]+58)};b.a.b.cd=function(a){var b=0,c="";if(0===a.length)return b;for(i=0;i<a.length;i++)c=a.charCodeAt(i),b=(b<<5)-b+c,b&=b;return b};b.a.b.md=function(a){a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");a=(new RegExp("[\\?&+]"+a+"=([^&#]*)")).exec(b.R());return b.g(a)?a[1]:!1};b.a.b.Xb=function(a,
b,c){return a[b]||a[c]};b.a.b.hd=function(a){a=a.replace(/[^0-9]/g,"");return 10==a.length||"1"==a[0]&&11==a.length};b.a.b.gd=function(a){return b.g(a.match(/^([a-zA-Z0-9_\.\-\+])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,6})+$/))};b.a.b.preventDefault=function(a){a&&a.preventDefault?a.preventDefault():b.global.event&&b.global.event.returnValue?b.global.eventReturnValue=!1:a.returnValue=!1};b.a.b.bind=function(a,b){var c,e,f=Function.prototype.bind,h=Array.prototype.slice;if(f&&a.bind===f)return f.apply(a,
h.call(arguments,1));c=h.call(arguments,2);return e=function(){if(!(this instanceof e))return a.apply(b,c.concat(h.call(arguments)));ctor.prototype=a.prototype;var f=ctor();ctor.prototype=null;var g=a.apply(f,c.concat(h.call(arguments)));return Object(g)===g?g:f}};b.a.b.ad=function(){var a=window.screen;return b.g(a)&&b.g(a.width)&&"number"==typeof a.width?{tc:a.width,ec:a.height}:{tc:0,ec:0}};b.a.b.Nc=function(a){for(var d=0,c,e=0;e<a.length&&b.g(a[e].c)&&b.g(a[e].p);e++)d+=a[e].p;c=b.a.b.lc(d);
for(e=d=0;e<a.length&&b.g(a[e].c)&&b.g(a[e].p);e++)if(d+=a[e].p,0<c&&c<=d)return a[e].c;return null};b.a.f={};b.stringify=b.global.JSON.stringify;b.parse=b.global.JSON.parse;b.a.o={};b.a.o.Fc=function(a,d){var c,e,f;b.g(a.length)||(a=[a]);c=0;for(e=a.length;c<e;c++){f=a[c];var h=f.className||"";(new RegExp("\\b"+d+"\\b")).test(h)||(f.className=(""===h?"":h+" ")+d)}};b.a.o.od=function(a,d){var c,e,f;b.g(a.length)||(a=[a]);c=0;for(e=a.length;c<e;c++)f=a[c],f.className&&(f.className=f.className.replace(new RegExp("(\\s|^)"+
d+"(\\s|$)")," ").replace(/^\s+|\s+$/g,""))};b.a.o.sa=function(a,d){if(a){b.g(a.length)||(a=[a]);for(var c=0;c<a.length;c++)for(var e in d)e&&(-1=="zIndex".indexOf(e)&&"number"==typeof d[e]&&"opacity"!=e&&(d[e]+="px"),a[c].style[e]=d[e])}};b.a.o.Hc=function(a,d){if(a){b.g(a.length)||(a=[a]);for(var c=0;c<a.length;c++)for(var e in d)a[c].setAttribute(e,d[e])}return a};b.a.o.outerHTML=function(a){return a.outerHTML};b.a.o.pd=function(a){function d(a){return function(b){if(9===b.keyCode)for(var d=0;d<
a.length;d++)if(a[d]===b.target){b.preventDefault?b.preventDefault():b.returnValue=!1;var c=d;if(b.shiftKey){do c=0===c?a.length-1:c-1;while((0>=a[c].offsetLeft||0>a[c].tabIndex)&&c!=d)}else{do c=(c+1)%a.length;while((0>=a[c].offsetLeft||0>a[c].tabIndex)&&c!=d)}a[c].focus();break}}}a=b.a.o.rb.nc("a, input[type=text], textarea, button, input[type=radio], select, *[tabIndex]",a).sort(function(a,b){return parseInt(a.tabIndex)>parseInt(b.tabIndex)});for(var c=0;c<a.length;c++){var e=a[c];b.a.b.l.La(e,
"keydown");b.a.b.l.ca(e,"keydown",d(a))}};b.a.o.dd=function(){for(var a=b.a.o.rb.nc("*",document.body),d=0;d<a.length;d++)b.a.o.sa(a[d],{display:"none"})};b.a.b.j=function(){this.da=[];this.ea=[]};b.a.b.j.prototype.q=function(a){this.ia?a(this.mc):this.da[this.da.length]=a;return this};b.a.b.j.prototype.resolve=function(a){if(!this.ia){this.ia=!0;this.mc=a;for(var b=0;b<this.da.length;b++)this.da[b](a)}};b.a.b.j.prototype.F=function(a){this.wa?a(this.reason):this.ea[this.ea.length]=a};b.a.b.j.prototype.reject=
function(a){if(!this.wa&&!this.ia){this.wa=!0;this.reason=a;for(var b=0;b<this.ea.length;b++)this.ea[b](a)}};b.a.b.j.all=function(a){function d(a){return function(b){a.reject(b)}}function c(a,b){return function(d){a.P++;a.Qa[b]=d;a.P===a.Jb.length&&a.resolve(a.Qa)}}var e=new b.a.b.j;e.Qa=[];e.P=0;e.Jb=a;for(var f=0;f<a.length;f++)a[f].q(c(e,f)).F(d(e));return e};b.Ia={};b.a.e={Bc:"br"};b.a.e.Za=function(){return"fsr.s"+(l.site.cookie?"."+l.site.cookie:"")};b.a.e.Sc=function(a,d){var c=b.a.e.bc(a,
d);if(!this.xb&&!b.tb&&!b.qb){var e;e="undefined"!=typeof acs?acs.makeURI("/foresee/"+l.iframeHrefs[0]):l.iframeHrefs[0];var f=new b.a.e.V(e,"fsr.s");setInterval(function(){var a=b.a.e.h.N("fsr.s");f.setItem("fsr.s",a)},2E3);this.xb=!0}return c};b.a.e.bc=function(a,d){var c=new b.a.b.j,e,f=b.a.e.Za();e=b.a.e.Ja(f,b.a.e.$a(f));e.I();(function(){if(b.g(a)){if(b.g(d))return e.set(a,d);"object"==typeof a||a instanceof Array||(a=[a]);var f=function(a,b,d,c){return function(e){d[a]=e;++c.P==b&&(1==c.P?
c.resolve(e):c.resolve(d),c.P=void 0)}};c.P=0;for(var g={},k=0;k<a.length;k++)e.get(a[k],!0).q(f(a[k],a.length,g,c))}else c.resolve(e)})();return c};b.a.e.Tc=function(a,d){var c;c=b.a.e.Za();c=b.a.e.Ja(c,b.a.e.$a(c));if("undefined"===typeof d)return c.ab(a);c.set(a,d)};b.a.e.$a=function(a){var d,c;c="undefined"!=typeof acs?acs.makeURI("/foresee/"+l.iframeHrefs[0]):"undefined"!==typeof acsMakeURI?acsMakeURI(l.iframeHrefs[0]):l.iframeHrefs[0];d="window"==l.storageOption&&b.a.e.ub.isSupported()?function(){var a=
arguments.callee;return new b.a.e.ub(a.ja,a.Xa||{})}:function(){var a=arguments.callee;return b.tb||b.qb?new b.a.e.Ha({ya:a.ja,G:a.ja,ua:c}):new b.a.e.h(a.ja,b.r({path:"/",domain:a.za.site.domain,secure:a.za.site.secure,encode:a.za.encode},a.Xa||{}))};d.ja=a;d.za=l;d.Xa=void 0;return d};var D={};b.a.e.Ja=function(a,d){var c=D[a];return b.g(c)?c:c=D[a]=new d};var B={width:"1",height:"1",id:"_"+Math.random().toString().slice(9),allowfullscreen:!0,allowscriptaccess:l.swf?l.swf.scriptAccess:"always",
version:[3,0],jc:null,Zb:null,Da:!1,Ub:!1};b.global.attachEvent&&b.global.attachEvent("onunload",function(){__flash_unloadHandler=function(){};__flash_savedUnloadHandler=function(){}});var s=b.r(b.Qc,{Kc:B,dc:function(){var a,b;try{b=navigator.plugins["Shockwave Flash"].description.slice(16)}catch(c){try{b=(a=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7"))&&a.GetVariable("$version")}catch(e){try{b=(a=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6"))&&a.GetVariable("$version")}catch(f){}}}return(b=
/(\d+)[^\d]+(\d+)[^\d]*(\d*)/.exec(b))?[b[1],b[3]]:[0,0]},pa:function(a){if(null===a||void 0===a)return null;var b=typeof a;"object"==b&&a.push&&(b="array");switch(b){case "string":return a=a.replace(RegExp('(["\\\\])',"g"),"\\$1"),a=a.replace(/^\s?(\d+\.?\d*)%/,"$1pct"),'"'+a+'"';case "array":return"["+H(a,function(a){return s.pa(a)}).join(",")+"]";case "function":return'"function()"';case "object":var b=[],c;for(c in a)a.hasOwnProperty(c)&&b.push('"'+c+'":'+s.pa(a[c]));return"{"+b.join(",")+"}"}return String(a).replace(/\s/g,
" ").replace(/\'/g,'"')},cc:function(a,d){a=b.r({},a);var c='<object width="'+a.width+'" height="'+a.height+'" id="'+a.id+'" name="'+a.id+'"';a.Ub&&(a.src+=(-1!=a.src.indexOf("?")?"&":"?")+Math.random());c=a.Da||!b.L?c+(' data="'+a.src+'" type="application/x-shockwave-flash"'):c+' classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"';c+=">";if(a.Da||b.L)c+='<param name="movie" value="'+a.src+'" />';a.width=a.height=a.id=a.Da=a.src=null;a.jc=a.version=a.Zb=null;for(var e in a)a[e]&&(c+='<param name="'+
e+'" value="'+a[e]+'" />');e="";if(d){for(var f in d)if(d[f]){var h=d[f];e+=f+"="+(/function|object/.test(typeof h)?s.pa(h):h)+"&"}e=e.slice(0,-1);c+='<param name="flashvars" value=\''+e+"' />"}return c+"</object>"},isSupported:function(a){return r[0]>a[0]||r[0]==a[0]&&r[1]>=a[1]}}),r=b.nb=s.dc();b.bb=b.g(r)&&0<r.length&&0<parseFloat(r[0]);b.bb||(r=b.nb=[0,0]);b.a.xc=A;b.a.v=function(){};p=(k=l.swf)?k.fileName:"foresee_transport.swf";"undefined"!=typeof acs&&(p=acs.makeURI(k?"foresee/"+k.fileName:
"foresee/foresee_transport.swf"));var I=p,v={};b.a.v.t=function(){if(this.w)try{this.w.parentNode.removeChild(flash_object),this.w.sendData=null,this.w.ping=null,this.w.isAlive=null}catch(a){}clearInterval(swftransport.Ma);b.aa(v)};b.a.v.isSupported=function(){return b.bb};b.a.v.A=function(a,d){if(this.w=b.Ta())return a.call(d,this);var c=b.global.document.createElement("div");c.id="_fsr_swfContainerv2";b.a.o.sa(c,{position:"absolute",top:1,left:1,width:1,height:1,minWidth:1,minHeight:1,padding:0,
margin:0,display:"block",visibility:"visible"});b.global.document.body.appendChild(c);var e=b.global.document.body;b.a.o.sa(c,{top:e.scrollTop+1,left:e.scrollLeft+1});A("_fsr_swfContainerv2",{src:I,id:"_fsr_swfContainerv2_"},{wmode:"transparent",allowScriptAccess:l.swf?l.swf.scriptAccess:"always",parentChild:b.global.top==b.global?"parent":"child"});this.Db(a,d)};b.a.v.Db=function(a,d){var c=b.a.v,e=this;c.Ma=setInterval(function(){var c=b.a.v;e.w=b.Ta();e.w&&e.w.isAlive&&a&&(clearInterval(c.Ma),
a.call(d,e),a=null)},500);c=null};b.Ia.yc="ac.uk co.uk gov.uk ltd.uk me.uk net.uk nhs.uk org.uk plc.uk police.uk sch.uk dni.us fed.us isa.us kids.us nsn.us ak.us al.us ar.us as.us az.us ca.us co.us ct.us dc.us de.us fl.us ga.us gu.us hi.us ia.us id.us il.us in.us ks.us ky.us la.us ma.us md.us me.us mi.us mn.us mo.us ms.us mt.us nc.us nd.us ne.us nh.us nj.us nm.us nv.us ny.us oh.us ok.us or.us pa.us pr.us ri.us sc.us sd.us tn.us tx.us ut.us vi.us vt.us va.us wa.us wi.us wv.us wy.us".split(" ");b.a.f.n=
function(a,d){b.na&&b.na.mb&&b.na.mb.Ic&&(d=!0);var c={method:"POST",url:b.R(),data:{},contentType:"application/x-www-form-urlencoded",la:b.M,X:b.M};this.kb=!1;var e=b.a.b.Xb;if(b.global.Worker&&!d){var f=b.a.b.qc,h=e(l.site,"js_files","files")||"";if(f(h,b.global.location.href))f=h+(l.worker||"foresee_worker.js"),"undefined"!=typeof acs&&(f=acs.makeURI(f)),this.Cb(f);else{var e=e(l.site,"html_files","files"),g=document.createElement("a");g.href=e;(this.Y=g.protocol+"//"+g.hostname+(g.port?":"+g.port:
""))&&f(e,h)&&(this.Bb(e+"iframe_proxier.html"),h!=e&&this.Ib(h+"foresee_worker.js"))}}this.options=b.r(c,a)};b.a.f.n.prototype.t=function(){this.Ea&&this.Ea.terminate();this.H&&(this.H.parentNode.removeChild(ifr),ifr=null);b.aa(this.options)};b.a.f.n.isSupported=function(){return b.L&&10>BROWSER.Sa.Sb&&"https"!=b.R().substring(0,5)&&b.global==b.global.top?!1:!0};b.a.f.n.A=function(a){a.call(b.a.f.n)};b.a.f.n.prototype.Bb=function(a){this.H=document.createElement("iframe");this.H.src=a;this.H.onload=
b.a.f.n.wb(this);this.H.style.display="none";document.body.appendChild(this.H);this.Ba=0;this.ka={};z(b.global,"message",function(a){return function(c){b.a.f.n.Na(a,c)}}(this))};b.a.f.n.prototype.Cb=function(a){try{this.Ea=new Worker(a),this.kb=!0}catch(d){}this.kb&&(this.Ba=0,this.ka={},this.Ea.onmessage=function(a){return function(d){b.a.f.n.Na(a,d)}}(this))};b.a.f.n.Na=function(a,d){if(!a.Y||a.Y===d.origin){var c=a.ka[d.data.i];switch(d.data.status){case 200:c.la&&c.la.call(c,d.data.rt);break;
case -1:b.na.Jc();break;default:c&&c.X&&c.X.call(c,d.data.rt)}delete a.ka[d.data.i]}};b.a.f.n.wb=function(a){return function(){a.fc=!0;if(a.O)for(var b=0;b<a.O.length;b++)a.Lb(a.O[b]);a.O=null}};b.a.f.n.prototype.Lb=function(a){var d=b.r(this.options,a);this.fc?(this.ka[++this.Ba]=d,this.H.contentWindow.postMessage(b.a.f.n.zb(d,this.Ba),this.Y)):this.O?this.O[this.O.length]=a:this.O=[a]};b.a.f.n.prototype.Ib=function(a){var b={m:"worker_url"};b.u=a;this.H.contentWindow.postMessage(b,this.Y)};b.a.f.n.zb=
function(a,b){var c={i:b},e=["method","url","data","contentType"],f;for(f in e)c[e[f]]=a[e[f]];return{m:"CORS",d:c}};b.a.f.U=function(a){this.options=b.r({url:"",data:"",Rc:"",qd:"",domain:"",version:"",kd:"",rd:"",la:b.M,X:b.M,Ac:1E4},a)};b.a.f.U.isSupported=function(){return b.a.v.isSupported()};b.a.f.U.A=function(a){b.a.v.A(a,b.a.f.U)};b.a.f.U.t=function(){b.a.v.t()};b.FlashTransportResponse=function(a,d){var c=b.parse(d);c.status&&0<c.status?v[a].Ec.call(v[a].Ob,d):v[a].Cc.call(v[a].Ob,d);delete v[a]};
var J=b.a.b.j;b.a.e.V=function(a,d){var c=this;b.ready(function(){c.J=c.vb(a);c.Ab=c.yb();"true"==c.J.getAttribute("data-ready")&&c.Oa()});this.oa=d;this.C=[];this.Q={};this.Pb=0;if(!this.oa)throw"FrameController requires a namespace";z(b.global,"message",b.a.b.bind(function(a){this.Eb(a)},this),"*")};var g=b.a.e.V;g.prototype.yb=function(){return/^(?:\/|[a-z]+:\/\/)/.test(this.J.src)?this.J.src:this.J.contentWindow.location.href};g.prototype.vb=function(a){var d=document.getElementById(a);if(b.g(d))return d;
d=document.createElement("iframe");d.src=a;d.id=a;d.className="ACS_";d.style.display="none";document.body.appendChild(d);return d};g.prototype.s=function(a,b){var c=new J,e=this.Pb++;this.Q[e]=c;this.Hb(e,a,b);this.Mb(c);return c};g.prototype.Mb=function(a){setTimeout(function(){a.ia||a.wa||a.reject("TIMEOUT")},1E4)};g.prototype.Hb=function(a,d,c){var e=b.stringify({id:a,namespace:this.oa,method:d,params:c});a=b.a.b.bind(function(){this.J.contentWindow.postMessage(e,"*")},this);this.Pa?a():this.Fb(a)};
g.prototype.Eb=function(a){a=g.prototype.Qb(a.data);if(this.Rb(a.src,a.namespace)&&!1!==a){this.Pa||this.Oa();var b=this.Q[a.id];if(b)switch(a.status){case 1:b.resolve(a.result);break;case -1:b.reject(a.result)}this.Q[a.id]=null}};g.prototype.Qb=function(a){var d;try{d=b.parse(a)}catch(c){return!1}return d};g.prototype.Rb=function(a,b){if(a){var c=!!a&&!!this.J&&a==this.Ab,e=!b||b==this.oa;return!a||c&&e}return!1};g.prototype.Oa=function(){this.J.setAttribute("data-ready",!0);this.Pa=!0;for(var a=
0;a<this.C.length;a++)this.C[a]();this.C=[]};g.prototype.Fb=function(a){this.C[this.C.length]=a};g.Dc=function(){for(var a in this.Q)this.Q[a]&&this.Q[a].reject("TIMEOUT")};g.prototype.flush=function(a){return this.s("flush",a)};g.prototype.buffer=function(a){return this.s("buffer",{value:a})};g.prototype.Ya=function(a,b){return this.s("flushAndBuffer",{nd:a,value:b})};g.prototype.setItem=function(a,b){return this.s("setItem",{key:a,value:b})};g.prototype.getItem=function(a){return this.s("getItem",
{key:a})};g.prototype.ib=function(a,b){return this.s("setAlive",{value:a,Pc:b})};g.prototype.gb=function(){return this.s("readAlive")};g.prototype.jb=function(){return this.s("setOptout")};g.prototype.hb=function(){return this.s("readOptout")};g.prototype.removeItem=function(a){return this.s("removeItem",{key:a})};g.prototype.fb=function(){return this.s("nuke")};g.isSupported=function(){return!!b.global.postMessage};var k=(b.a.b.lb=function(){this.K=[]}).prototype,y=b.a.b.bind;k.Wa=function(a,b){this.K.push({ac:a,
Vb:b,Tb:void 0});1===this.K.length&&a.apply(b||{},[]).q(y(function(){this.fa()},this)).F(y(function(){this.fa()},this))};k.fa=function(){this.K.shift();var a=this.K[0];"undefined"!==typeof a&&a.ac.apply(a.Vb||this,a.Tb||[]).q(y(function(){this.fa()},this)).F(y(function(){this.fa()},this))};b.a.b.l={};b.a.b.l.T={};b.a.b.l.ca=function(a,d,c,e){var f=b.a.b.l.T;if(a){f[d]||(f[d]=[]);f[d].push({Va:a,qa:c});if("unload"==d){if(b.g(b.ba)){b.ba.push(c);return}b.ba=[]}"propertychange"!=d&&a.addEventListener?
a.addEventListener(d,c,!e):a.attachEvent&&a.attachEvent("on"+d,c)}};b.a.b.l.uc=function(a,d,c,e,f){var h=b.a.b.l;if(f){if(a.getAttribute("_fsr"+d))return!1;a.setAttribute("_fsr"+d,"true")}else if(f=h.T[d])for(h=f.length-1;0<=h;h--)if(f[h].Va==a&&(e||f[h].qa==c))return!1;b.a.b.l.ca(a,d,c)};b.a.b.l.vc=function(a,d,c){b.a.b.l.ca(a,d,c,!0)};b.a.b.l.La=function(a,b,c){try{"propertychange"!=b&&a.removeEventListener?a.removeEventListener(b,c,!0):a.detachEvent&&a.detachEvent("on"+b,c)}catch(e){}};var z=b.a.b.l.ca;
b.a.b.l.pb=function(){for(var a=b.ba.length-1;0<=a;a--)try{b.ba[a].call()}catch(d){}b.aa(b.ba);b.a.b.l.sb();b.t()};z(b.global,"unload",b.a.b.l.pb);b.a.b.l.sb=function(){if(b){var a=b.a.b.l,d;for(d in a.T){for(var c=a.T[d],e=c.pop();e;)a.La(e.Va,d,e.qa),b.aa(e),e=c.pop();delete a.T[d]}}};b.a.b.l.Ga=function(){this.Aa=[]};b.a.b.l.Ga.prototype.$b=function(){for(var a=0;a<this.Aa.length;a++){var b=this.Aa[a];b.qa.apply(this,arguments);b.ld&&(this.Aa.splice(a,1),a--)}};var E=b.a.b.l.Ga;b.a.e.Ha=function(a){this.ua=
a.ua;this.ya=a.ya;this.G=a.G;this.Ka=new E;this.k={};this.K=new b.a.b.lb;this.A()};k=b.a.e.Ha;k.prototype.A=function(){this.cb=new b.a.e.V(this.ua,this.ya)};k.prototype.set=function(a,d){var c=new b.a.b.j,e=this;"undefined"===typeof d&&(d=a,a=void 0);this.K.Wa(function(){e.I().q(function(){"undefined"===typeof a?e.k=d:e.k[a]=d;e.D().q(function(){c.resolve()})});return c},this);return c};k.prototype.get=function(a){var d=new b.a.b.j,c=this;this.K.Wa(function(){c.I().q(function(){"undefined"!=typeof a?
d.resolve(c.k[a]):d.resolve(c.k)});return d},this);return d};k.prototype.ab=function(a){return"undefined"!==typeof a?this.k[a]:this.k};k.prototype.reset=function(a){this.k=a||{};this.D()};k.prototype.t=function(a){return this.set(a,void 0)};k.prototype.eb=function(){return this.reset()};k.prototype.Nb=function(){};k.prototype.I=function(a,d,c){var e=new b.a.b.j,f=this;this.N(this.G).q(function(b){f.Gb(e,b);"function"===typeof a&&a.apply(d||{},c)}).F(this.Nb);return e};k.prototype.Gb=function(a,d){try{this.k=
b.parse(d.value||"{}"),b.g(this.k)||(this.k={})}catch(c){this.k={}}a.resolve()};k.prototype.D=function(){var a=new b.a.b.j,d=b.stringify(this.k),c=b.a.b.bind(function(c){a.resolve(b.parse(c.value))},this),e=b.a.b.bind(function(){a.reject("Storage full")},this);this.write(this.G,d).q(c).F(e);return a};k.prototype.t=function(a){this.I();"undefined"!==typeof a?delete this.k[a]:this.k={};this.D()};k.prototype.write=function(a,b){return this.cb.setItem(a,b)};k.prototype.N=function(a){return this.cb.getItem(a)};
k.prototype.isSupported=function(){return b.a.e.V.isSupported()};b.a.e.h=function(a,d){a||(a="fsr.STORAGE");this.G=a.replace(/[- ]/g,"");b.a.e.h.k||b.a.e.h.A();this.$=d||{};this.data={};this.Ka=new E;this.pc=4E3};b.a.e.h.prototype.set=function(a,d){this.I();this.k[a]=d;this.D();var c=new b.a.b.j;c.resolve(d);return c};b.a.e.h.prototype.reset=function(a){this.k=a;this.D()};b.a.e.h.prototype.get=function(a,d){var c=new b.a.b.j;this.I();var e;e=a?this.k[a]:this.k;return d?(c.resolve(e),c):e};b.a.e.h.prototype.ab=
function(a){return this.get(a,!1)};b.a.e.h.prototype.t=function(a){this.I();delete this.k[a];this.D()};b.a.e.h.prototype.eb=function(){this.k={};var a=this.$.duration;this.$.duration=-1;this.D();a?this.$.duration=a:delete this.$.duration};b.a.e.h.prototype.I=function(a,d,c){var e=new b.a.b.j;this.k={};try{var f=b.a.e.h.N(this.G);f&&0<f.length&&(this.k=b.parse(f),b.g(this.k)||(this.k={}),"function"===typeof a&&a.apply(d||{},c))}catch(g){this.k={}}e.resolve();return e};b.a.e.h.prototype.D=function(){var a=
b.stringify(this.k);this.G.length+b.ga(a).length>this.pc&&this.Ka.$b(this);b.a.e.h.write(this.G,a,this.$)};b.a.e.h.N=function(a){return(a=b.global.document.cookie.match("(?:^|;)\\s*"+b.Yb(a)+"=([^;]*)"))?b.ta(a[1]):null};b.a.e.h.write=function(a,d,c){d=c&&b.g(c.encode)&&!c.encode?d:b.ga(d);a=b.ga(a);for(var e in c)if(c[e]){var f=c[e];d+=";"+("duration"===e?"expires":e);switch(e){case "duration":d+="="+(new Date(b.now()+f*b.ob)).toGMTString();break;default:d+="="+f}}b.global.document.cookie=a+"="+
d;return a.length+d.length+2};b.a.e.h.eb=function(a,d){b.a.e.h.write(a,"",b.r(d,{duration:-1}))};b.a.e.h.A=function(a){a&&a.apply(b.a.e.h)};b.a.e.h.isSupported=function(){return!0};b.a.f.B={};b.a.f.B.C=[];b.a.f.B.ready=function(a){if(b.a.f.B.hc)a();else{var d=b.a.f.B.C;d[d.length]=a}};b.ready(function(){b.a.f.B.zc={XHR:b.a.f.S,SWF:b.a.f.U,CORS:b.a.f.n};for(var a=b.a.f.B.C,d=0;d<a.length;d++)a[d]();b.a.f.B.hc=!0});b.a.f.B.Yc=function(a){for(var d,c=null,e=0;e<a.rc.length;e++){c=a.rc[e];try{if(c.isSupported()){d=
c;break}}catch(f){}}b.g(d)?d.A(a.ready):a.X.call()};g=function(){this.ma="__FSR__BUFFER__";this.Fa=window.Fa||5E6;this.W=new b.a.e.h;this.oc();this.postMessage(-1,0,"","ready")};g.prototype.oc=function(){function a(a){b.kc(a)}var b=this;window.addEventListener?window.addEventListener("message",a,!1):window.attachEvent&&window.attachEvent("onmessage",a)};g.prototype.kc=function(a){try{var d=b.parse(a.data);d.namespace&&this.Kb(d)}catch(c){}};g.prototype.Kb=function(a){var d=a.params,c="_IFR_"+l.site_id+
"_"+a.namespace;switch(a.method){case "setItem":promise=this.setItem(c,d.key,d.value);break;case "getItem":promise=this.getItem(c,d.key);break;case "removeItem":promise=this.removeItem(c,d.key);break;case "nuke":promise=this.fb(c);break;case "buffer":promise=this.buffer(c,d.value);break;case "flush":promise=this.flush(c,d);break;case "flushAndBuffer":promise=this.Ya(c,d.params,d.value);break;case "setAlive":promise=this.ib(c,d.value,d.expires);break;case "readAlive":promise=this.gb(c);break;case "setOptout":promise=
this.jb(c);break;case "readOptout":promise=this.hb(c);break;default:promise=this.sc(a.method)}promise.q(b.a.b.bind(function(b){this.postMessage(a.id,1,a.namespace,b)},this));promise.F(b.a.b.bind(function(b){this.postMessage(a.id,-1,a.namespace,b)},this))};g.prototype.postMessage=function(a,d,c,e){window.parent.postMessage(b.stringify({id:a,result:e,namespace:c,status:d,src:b.global.location.href}),"*")};g.prototype.setItem=function(a,d,c){var e=new b.a.b.j;try{this.W.set(a+"."+d,c),e.resolve({key:d,
value:c})}catch(f){e.reject("STORAGE_FULL")}return e};g.prototype.getItem=function(a,d){var c=new b.a.b.j;c.resolve({value:this.W.get(a+"."+d)});return c};g.prototype.removeItem=function(a,d){var c=new b.a.b.j;this.W.t(a+"."+d);c.resolve({key:d});return c};g.prototype.flush=function(a){var d=new b.a.b.j,c=localStorage.getItem(a+"."+this.ma);this.W.set(a+"."+this.ma,"");d.resolve({data:c});return d};g.prototype.buffer=function(a,d){var c=new b.a.b.j,e=a+"."+this.ma,f=this.W.get(e)||"";if(f.length+
d.length<=this.Fa)try{localStorage.setItem(e,f+d),c.resolve({data:d})}catch(g){c.reject("STORAGE_FULL")}else c.reject("STORAGE_FULL");return c};g.prototype.Ya=function(a,d){var c=new b.a.b.j,e=this.flush(a),f=this;e.q(function(){var b=f.buffer(a,d);b.q(c.resolve);b.F(c.reject)});e.F(c.reject);return c};g.prototype.fb=function(a){var d=new b.a.b.j,c;for(c in localStorage)0===c.indexOf(a+".")&&localStorage.removeItem(c);d.resolve();return d};g.prototype.ib=function(a,d,c){var e=new b.a.b.j;"undefined"===
typeof d&&(d=b.now());if(!b.g(l.heartbeat)||l.heartbeat){var f={path:"/",secure:l.site.secure};c&&(f.expires="-1");b.a.e.h.write(a,d,f);e.resolve();return e}};g.prototype.gb=function(a){var d=new b.a.b.j;a=b.a.e.h.N(a,{path:"/",domain:l.site.domain,secure:l.site.secure});d.resolve(a);return d};g.prototype.jb=function(a){var d=new b.a.b.j,c=new Date;c.setTime(c.getTime()+31536E6);b.a.e.h.write(a,"365",{path:"/",expires:c.toGMTString()});d.resolve();return d};g.prototype.hb=function(a){var d=new b.a.b.j;
a=b.a.e.h.N(a,{path:"/",domain:l.site.domain,secure:l.site.secure});d.resolve(a);return d};g.prototype.sc=function(a){var d=new b.a.b.j;d.reject("UNKNOWN METHOD: "+a);return d};setTimeout(function(){b.Ia.V=g=new g},1);b.a.f.S=function(a){this.options=b.r({method:"POST",url:b.R(),data:{},contentType:"application/x-www-form-urlencoded",la:b.M,X:b.M},a)};b.a.f.S.prototype.t=function(){b.aa(this.options)};b.a.f.S.isSupported=function(){return!0};b.a.f.S.A=function(a){a.call(b.a.f.S)}}(F);
