#!/usr/bin/env bash

if
  [[ -s "/Users/CloudFactory/.rvm/gems/ruby-2.1.4@global/environment" ]]
then
  source "/Users/CloudFactory/.rvm/gems/ruby-2.1.4@global/environment"
  exec erb "$@"
else
  echo "ERROR: Missing RVM environment file: '/Users/CloudFactory/.rvm/gems/ruby-2.1.4@global/environment'" >&2
  exit 1
fi
